Выполнить задание согласно требованиям ТЗ 9
am29-10/java-filmorate pull request #7
Opened 2022-08-06 16:05 UTC by am29-10

2022-08-07 12:52 UTC, sergeymamonov requested changes
Можно заметить, что для контроллера фильмов и пользователей методы схожи, а значит можно создать базовый класс с одинаковыми для классов наследников (контроллеров) методами. И в нем определить базовое поведение (создание, изменение, получение). Не настаиваю на создании базового класса, но попробовать можете.

2022-08-07 12:52 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
Лучше заданные числа выделять в константы. Если в будущем они изменятся, то поменять придется всего лишь в одном месте.

2022-08-07 12:52 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895,12,28))) {
Дату лучше в константу сохранить.

2022-08-07 12:52 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new NoUserFoundException("Список пользователей пуст");
Немного странное поведение, что если юзеров нет, то кидается ошибка. Логичнее вернуть пустой массив. Аналогично с фильмами

2022-08-07 12:52 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +        film.setDescription("«Властелин колец» является одним из самых крупных проектов в истории кино, " +
Так лучше не проверять ограничение в количестве символов. В тестах все должно быть явно. Либо создать массив из 201 символа, либо "a".repeat(201)

2022-08-08 09:55 UTC, am29-10 commented
Интерфейс контроллера пока создавать не стал, хотя, согласно одному из принципов SOLID, вроде как нужно. Если новые методы в контроллерах так же будут схожи в следующих тз, то попробую сделать через интерфейс. Спасибо

2022-08-08 21:27 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmServiceImpl.java
> +    private static final LocalDate birthdayMovie = LocalDate.of(1895,12,28);
Это же константы, а значит написаны должны быть заглавными буквами через нижнее подчеркивание

2022-08-08 21:34 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserServiceImpl.java
> +            log.info("NoMovieFoundException (Фильм не может быть обновлен, т.к. его нет в списке)");
Здесь обновляются данные о юзере.

2022-08-08 21:37 UTC, sergeymamonov commented
Проверьте, используется ли теперь класс NoUserFoundException. При отсутствии пользователя/фильма при обновлении можно кидать одну общую ошибку, например EntityNotFound, чтобы не создавать лишних классов ошибок.

2022-08-08 21:37 UTC, sergeymamonov approved these changes

2022-08-14 09:37 UTC, merged