Add friends likes
am29-10/java-filmorate pull request #8
Opened 2022-08-18 17:29 UTC by am29-10

ТЗ-10

2022-08-19 14:45 UTC, sergeymamonov requested changes
Проверить классы на предмет не используемых импортов.

2022-08-19 14:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Посмотрите, какие еще могут быть ошибки, 409, 500.

2022-08-19 14:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        validate(film);
Валидацию нужно делать в сервисе, а не здесь. Аналогично для пользователей.

2022-08-19 14:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
>      private static int id;
это поле должно быть в сервисе, сюда уже должны приходить готовые объекты.

2022-08-19 14:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
>          if (film.getId() == 0) {
Перенесите id в сервис и такая проверка не будет нужна.

2022-08-19 14:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
>          films.put(film.getId(), film);
А если придет из сервиса фильм с существующим в мапе id? Такую проверку лучше сделать.

2022-08-19 14:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage());
Можно добавить логирования.

2022-08-19 14:45 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Замечания, аналогичные замечаниям в InMemoryFilmStorage

2022-08-22 22:55 UTC, am29-10 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Искал в интернете, не нашел пример обработки 500 ошибки. А по поводу 409, пока не понимаю, где может возникнуть конфликт. Спасибо

2022-08-23 03:35 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
@ExceptionHandler
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
      public ErrorResponse handleThrowable(final Throwable e) {
      log.info("500 {}", e.getMessage(), e);
      return new ErrorResponse(e.getMessage());
}

409 - это конфликт, когда хотим сохранить сущность, а она уже есть в БД. В нашем случае в стораже перед записью сделать проверку, есть ли в мапе уже значение с таким id (и для фильмов и для юзеров).

2022-08-23 03:42 UTC, sergeymamonov approved these changes

2022-08-30 15:56 UTC, merged